version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: excon
    versions:
    - 0.78.1
    - 0.79.0
  - dependency-name: newrelic_rpm
    versions:
    - 6.15.0
  - dependency-name: fog-aws
    versions:
    - 3.8.0
  - dependency-name: loofah
    versions:
    - 2.9.0
